version: '3'

services:

  webapp-service.io:
    env_file: ./dev.env
    build: ./docker-core/opplett-webapp/
    image: opplett/webapp:latest
    volumes:
      - ./:/workdir
    ports:
      - "5555:5555"
    links:
      - postgres-service
      - redis-service
    restart: on-failure
    depends_on:
      - postgres-service
      - redis-service
    command:
      [python, app.py]


  webpack-dev-server-service:
    build: ./docker-core/opplett-webapp/
    image: opplett/webapp:latest
    volumes:
      - ./:/workdir
    ports:
      - "8080:8080"
    links:
      - webapp-service.io
    command:
      ["bash", "-c", "npm install --save --save-dev && npm run webpack-dev-server"]


  webpack-watch-service:
    build: ./docker-core/opplett-webapp/
    image: opplett/webapp:latest
    volumes:
      - ./:/workdir
    links:
      - webapp-service.io
    command:
      ["bash", "-c", "npm install --save --save-dev && npm run webpack-watch"]


  compute-service:
    env_file: ./dev.env
    build: ./docker-core/opplett-compute/
    image: opplett/compute:latest
    volumes:
      - ./:/workdir
    command:
      [python, ./compute/main.py]


  redis-service:
    image: redis:3.0


  postgres-service:
    image: postgres:9.6
    env_file: ./dev.env
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/opplett_pg_data:/var/lib/postgresql"